baseURL = "https://fred3ric.github.io/"
languageCode = "en-us"
title = "Frederic R."
theme = "yinyang"
enableRobotsTXT = true
pygmentsUseClasses = true

[author]
  email = "fred@fred.com"
  name = "Fr3deric"

[params]
  headTitle = "Fr3deric ğŸ§‘ğŸ»â€ğŸ’»ğŸ§¬"
  mainSections = ["blog"]
  favicon = "/img/favicon.ico"
  images = ["/img/belle-ile.jpg"]
  description = "Fr3deric's blog ãƒ„"

[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
